export const LOTS_DATA = [
  {
    id: "lot-001",
    name: "BMW X5 2021",
    country: "USA",
    auction: "Copart",
    currentBid: 12500,
    image: "/assets/images/car1.jpg",
    specs: {
      engine: "3.0L I6 Turbo",
      mileage: "28 000 mi",
      damage: "Minor front-end",
    },
    costBreakdown: {
      bid: 12500,
      auctionFee: 750,
      shipping: 1800,
      customs: 4200,
      serviceFee: 500,
      total: 19750,
    },
    description: "Clean Carfax, one owner, runs and drives. Minor bumper damage.",
  },
  {
    id: "lot-002",
    name: "Toyota Land Cruiser 2020",
    country: "Japan",
    auction: "USS Tokyo",
    currentBid: 22000,
    image: "/assets/images/car2.jpg",
    specs: {
      engine: "4.5L V8 Diesel",
      mileage: "35 000 km",
      damage: "Hail damage (roof)",
    },
    costBreakdown: {
      bid: 22000,
      auctionFee: 1100,
      shipping: 2500,
      customs: 6800,
      serviceFee: 700,
      total: 33100,
    },
    description: "Excellent interior, needs body work on roof. Very rare in RF.",
  },
  {
    id: "lot-003",
    name: "Hundai",
    country: "korean",
    auction: "BCA EU",
    currentBid: 18500,
    image: "/assets/images/car3.jpg",
    specs: {
      engine: "3.0L V6",
      mileage: "18 000 km",
      damage: "Rear-end collision",
    },
    costBreakdown: {
      bid: 18500,
      auctionFee: 950,
      shipping: 2100,
      customs: 5100,
      serviceFee: 600,
      total: 27250,
    },
  },
  {
    id: "lot-004",
    name: "Tesla Model Y 2023",
    country: "USA",
    auction: "IAAI",
    currentBid: 15800,
    image: "/assets/images/car4.jpg",
    specs: {
      engine: "Electric Dual Motor",
      mileage: "12 000 mi",
      damage: "Flood (non-structural)",
    },
    costBreakdown: {
      bid: 15800,
      auctionFee: 850,
      shipping: 1900,
      customs: 2000,
      serviceFee: 550,
      total: 21100,
    },
  },
  {
    id: "lot-005",
    name: "Mercedes-Benz GLE 450 2022",
    country: "USA",
    auction: "Copart",
    currentBid: 19700,
    image: "/assets/images/car5.jpg",
    specs: {
      engine: "3.0L I6 Mild Hybrid",
      mileage: "22 000 mi",
      damage: "Side swipe",
    },
    costBreakdown: {
      bid: 19700,
      auctionFee: 1020,
      shipping: 1850,
      customs: 5900,
      serviceFee: 650,
      total: 29120,
    },
  },
];